#ifndef IMC_ID_DEF_
#define IMC_ID_DEF_

#define IMC_ID_ENTITYLIST 5
#define IMC_ID_ENTITYACTIVATIONSTATE 14
#define IMC_ID_QUERYENTITYACTIVATIONSTATE 15

#define IMC_ID_HEARTBEAT 150
#define IMC_ID_ANNOUNCE 151

#define IMC_ID_GROUNDVELOCITY 259
#define IMC_ID_WATERVELOCITY 260
#define IMC_ID_TEMPERATURE 263
#define IMC_ID_PRESSURE 264
#define IMC_ID_DEPTH 265
#define IMC_ID_SOUNDSPEED 267
#define IMC_ID_CONDUCTIVITY 269
#define IMC_ID_SALINITY 270
#define IMC_ID_FUELLEVEL 279

#define IMC_ID_ESTIMATEDSTATE 350

#define IMC_ID_STATIONKEEPING 461
#define IMC_ID_FOLLOWREFSTATE 480

#define IMC_ID_VEHICLESTATE 500
#define IMC_ID_ABORT 550
#define IMC_ID_PLANCONTROL 559
#define IMC_ID_PLANCONTROLSTATE 560

#define IMC_ID_ENTITYPARAMETERS 802
#define IMC_ID_QUERYENTITYPARAMETERS 803
#define IMC_ID_SETENTITYPARAMETERS 804
#define IMC_ID_SAVEENTITYPARAMETERS 805
#define IMC_ID_IOEVENT 813

#define IMC_ID_ABORTED 889



#endif
